sudo: required

language: java
jdk:
  - oraclejdk8

services:
  - docker

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    mvn -Pprod docker:build
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push microcks/microcks:latest;
    fi