version: '2'
services:
  mongo:
    image: mongo:3.3.12
    container_name: microcks-mongo
    volumes:
      - "~/tmp/microcks-data:/data/db"
  app:
    depends_on:
      - mongo
    image: lbroudoux/microcks:latest
    container_name: microcks
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017
      - SPRING_DATA_MONGODB_DATABASE=microcks
    links:
      - mongo:mongo
