version: '2'
networks:
  main:
services:
  mongo:
    image: mongo:3.3.12
    container_name: microcks-mongo
    volumes:
      - "~/tmp/microcks-data:/data/db"
    networks:
      main:
        aliases:
          - mongo
  postman:
    image: microcks/microcks-postman-runtime:latest
    container_name: microcks-postman-runtime
    networks:
      main:
        aliases:
          - postman
  app:
    depends_on:
      - mongo
      - postman
    image: microcks/microcks:latest
    container_name: microcks
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017
      - SPRING_DATA_MONGODB_DATABASE=microcks
      - POSTMAN_RUNNER_URL=http://postman:3000
      - TEST_CALLBACK_URL=http://microcks:8080
    networks:
      main:
        aliases:
          - microcks
