kind: Secret
apiVersion: v1
metadata:
  name: "{{ .Values.appName }}-mongodb-connection"
  labels:
    app: "{{ .Values.appName }}"
    container: mongodb
    group: microcks
type: kubernetes.io/basic-auth
stringData:
  username: "{{ .Values.mongodbUsername }}"
data:
  {{- if .Values.mongodbPassword }}
  password: {{ .Values.Master.mongodbPassword | b64enc | quote }}
  {{- else }}
  password: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
  adminPassword: {{ randAlphaNum 40 | b64enc | quote }}
---
kind: Secret
apiVersion: v1
metadata:
  name: "{{ .Values.appName }}-keycloak-admin"
  labels:
    app: "{{ .Values.appName }}"
    container: keycloak
    group: microcks
type: kubernetes.io/basic-auth
stringData:
  username: "{{ .Values.keycloakAdminUsername }}"
  postgresUsername: "{{ .Values.postgresUsername }}"
data:
  {{- if .Values.keycloakAdminPassword }}
  password: {{ .Values.Master.keycloakAdminPassword | b64enc | quote }}
  {{- else }}
  password: {{ randAlphaNum 40 | b64enc | quote }}
  {{- end }}
  {{- if .Values.postgresPassword }}
  postgresPassword: {{ .Values.Master.postgresPassword | b64enc | quote }}
  {{- else }}
  postgresPassword: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}